var mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/webchat')
exports.User = mongoose.model('User', require('./user'))
exports.Message = mongoose.model('Message', require('./message'))
exports.Group = mongoose.model('Group', require('./group'))
exports.Apply = mongoose.model('Apply', require('./apply'))
